name: Push Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build Docker image
        run: ./mvnw spring-boot:build-image -DskipTests
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag local image
        run: docker tag spring-petclinic:3.4.0-SNAPSHOT ghcr.io/${{ github.repository_owner | toLower }}/spring-petclinic:3.4.0-SNAPSHOT

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner | toLower }}/spring-petclinic:3.4.0-SNAPSHOT
